Fix issue with bower module
Lodash.get is not available in client side bundle so caused an
error in bower module export.
```Cannot complete build due to compilation error from build tools:
./bower_components/n-swg/src/client/swg-controller.js Module not
found: Error: Can't resolve 'lodash.get' in
'./bower_components/n-swg/src/client'```

Rather than depend on lodash I have added a simple util to
replace its limited usage.

 🐿 v2.7.0